version: '2'
services: 
  firefox:
    image: selenium/node-firefox:latest
    ports:
      - 5900
    volumes:
      - /dev/shm:/dev/shm
    depends_on: 
      - hub
    environment:
      HUB_HOST: hub
      NODE_MAX_INSTACES: 2
      NODE_MAX_SESSION: 2
  
  chrome:
    image: selenium/node-chrome:latest
    ports:
      - 5900
    volumes: 
      - /dev/shm:/dev/shm
    depends_on: 
      - hub
    environment: 
      HUB_HOST: hub
      NODE_MAX_INSTANCES: 2
      NODE_MAX_SESSION: 2
  
  hub:
    image: selenium/hub:latest
    ports: 
      - "4444:4444"
  
  jenkins:
    image: 'jenkins/jenkins:lts'
    labels:
      kompose.service.type: nodeport
    ports:
      - '8080:8080'
      - '443:8443'
      - '50000:50000'
    volumes:
      - 'jenkins_data:/jenkins_config'
volumes:
  jenkins_data:
    driver: local