version: '2'
services: 
  firefox:
    image: selenium/node-firefox-debug:latest
    ports:
      - 5900
    volumes:
      - /dev/shm:/dev/shm
    depends_on: 
      - hub
    environment:
      HUB_HOST: hub
      NODE_MAX_INSTACES: 2
      NODE_MAX_SESSION: 2
  
  chrome:
    image: selenium/node-chrome-debug:latest
    ports:
      - 5900
    volumes: 
      - /dev/shm:/dev/shm
    depends_on: 
      - hub
    environment: 
      HUB_HOST: hub
      NODE_MAX_INSTANCES: 2
      NODE_MAX_SESSION: 2
  
  hub:
    image: selenium/hub:latest
    ports: 
      - "4444:4444"
  